### ISSUE TITLE
Create demo project

### ISSUE THREAD

**Issue by arivera12** [arivera12/BlazorCurrentDevice#3]
Include .gif image with demo in readme.md

**Comment by colinbracey** [comment]
A demo project showing all the options would be just perfect.
Thank you!

**Comment by arivera12** [comment]
@colinbracey I added demo project, documentation and migrated to interface based service. 

**NOTE:** Upgrade your package to latest version: `Install-Package BlazorCurrentDevice -Version 1.0.6`

**Breaking Changes:** Change _BlazorCurrentDeviceService_ to _IBlazorCurrentDeviceService_. 

I also added .gif of the demo on the main repository page. 

Please read the main page again for more info.

> A demo project showing all the options would be just perfect.
> Thank you!

Looking at your code you send me on the email you missed the `await` operator.

`var p = await BlazorCurrentDeviceService.OS();`
Or
`var x = await BlazorCurrentDeviceService.Type();`
